### ISSUE TITLE
Coverage report should be red when under 75%

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-jenkins-plugin#6]
Our project is at 74.26% coverage but for some reason it is not shown as red in the report.

![image](https://cloud.githubusercontent.com/assets/2373097/7771890/427b772e-0060-11e5-898a-1370ab376261.png)

**Comment by naverus** [comment]
Hi @ndorotte JIC, this bug was fixed on 1.0.3 version, the Jenkins plugin is available at.

https://bintray.com/artifact/download/fundacionjala/enforce/org/fundacionjala/gradle/plugins/enforce/enforce-gradle-plugin/1.0.3/enforce-jenkins-plugin.hpi
